# Generated by Django 5.2 on 2025-08-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_start_t_c2d277_idx',
            old_name='events_even_start_t_6c54f5_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_is_publ_cc4b67_idx',
            old_name='events_even_is_publ_5f8db8_idx',
        ),
    ]
